# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('nickname', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7528\u6237\u6635\u79f0')),
                ('email', models.EmailField(max_length=255, verbose_name='\u90ae\u7bb1\u5730\u5740')),
                ('phonenum', models.CharField(max_length=32, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_del', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
